from __future__ import annotations

from backend.app.db import Base, SessionLocal, engine
from backend.app.main import upsert_entries
from backend.app.schemas import EntryCreate


RAW_ITEMS = [
    ("die Pfanne", "die Pfannen", "平底锅", "kitchen", "frying pan"),
    ("der Topf", "die Töpfe", "锅", "kitchen", "cooking pot"),
    ("das Messer", "die Messer", "刀", "kitchen", "knife"),
    ("die Gabel", "die Gabeln", "叉子", "kitchen", "fork"),
    ("der Löffel", "die Löffel", "勺子", "kitchen", "spoon"),
    ("der Teller", "die Teller", "盘子", "kitchen", "plate"),
    ("die Schüssel", "die Schüsseln", "碗；大碗", "kitchen", "bowl"),
    ("die Tasse", "die Tassen", "杯子", "kitchen", "cup"),
    ("das Glas", "die Gläser", "玻璃杯", "kitchen", "drinking glass"),
    ("die Flasche", "die Flaschen", "瓶子", "kitchen", "bottle"),
    ("der Kühlschrank", "die Kühlschränke", "冰箱", "kitchen", "refrigerator"),
    ("der Ofen", "die Öfen", "烤箱", "kitchen", "oven"),
    ("die Mikrowelle", "die Mikrowellen", "微波炉", "kitchen", "microwave oven"),
    ("der Wasserkocher", "die Wasserkocher", "电水壶", "kitchen", "electric kettle"),
    ("das Schneidebrett", "die Schneidebretter", "砧板", "kitchen", "cutting board"),
    ("die Spüle", "die Spülen", "水槽", "kitchen", "kitchen sink"),
    ("der Schwamm", "die Schwämme", "海绵", "kitchen", "sponge"),
    ("das Geschirrtuch", "die Geschirrtücher", "擦碗布", "kitchen", "dish towel"),
    ("die Zahnbürste", "die Zahnbürsten", "牙刷", "bathroom", "toothbrush"),
    ("die Zahnpasta", "die Zahnpasten", "牙膏", "bathroom", "toothpaste"),
    ("das Handtuch", "die Handtücher", "毛巾", "bathroom", "towel"),
    ("der Spiegel", "die Spiegel", "镜子", "bathroom", "mirror"),
    ("die Seife", "die Seifen", "肥皂", "bathroom", "soap"),
    ("das Shampoo", "die Shampoos", "洗发水", "bathroom", "shampoo bottle"),
    ("die Dusche", "die Duschen", "淋浴", "bathroom", "shower"),
    ("die Badewanne", "die Badewannen", "浴缸", "bathroom", "bathtub"),
    ("die Toilette", "die Toiletten", "马桶；厕所", "bathroom", "toilet"),
    ("der Kamm", "die Kämme", "梳子", "bathroom", "comb"),
    ("der Rasierer", "die Rasierer", "剃须刀", "bathroom", "razor"),
    ("der Tisch", "die Tische", "桌子", "furniture", "table"),
    ("der Stuhl", "die Stühle", "椅子", "furniture", "chair"),
    ("das Sofa", "die Sofas", "沙发", "furniture", "sofa"),
    ("das Bett", "die Betten", "床", "furniture", "bed"),
    ("der Schrank", "die Schränke", "柜子；衣柜", "furniture", "wardrobe cabinet"),
    ("das Regal", "die Regale", "架子；书架", "furniture", "shelf"),
    ("die Lampe", "die Lampen", "灯", "furniture", "lamp"),
    ("der Vorhang", "die Vorhänge", "窗帘", "furniture", "curtain"),
    ("das Kissen", "die Kissen", "枕头；靠垫", "furniture", "pillow"),
    ("die Decke", "die Decken", "毯子；被子", "furniture", "blanket"),
    ("der Teppich", "die Teppiche", "地毯", "furniture", "carpet"),
    ("der Hammer", "die Hämmer", "锤子", "tools", "hammer"),
    ("der Schraubenzieher", "die Schraubenzieher", "螺丝刀", "tools", "screwdriver"),
    ("die Zange", "die Zangen", "钳子", "tools", "pliers"),
    ("die Schere", "die Scheren", "剪刀", "tools", "scissors"),
    ("die Säge", "die Sägen", "锯子", "tools", "saw tool"),
    ("der Nagel", "die Nägel", "钉子", "tools", "nail hardware"),
    ("die Schraube", "die Schrauben", "螺丝", "tools", "screw hardware"),
    ("das Klebeband", "die Klebebänder", "胶带", "tools", "adhesive tape"),
    ("der Pinsel", "die Pinsel", "刷子；画笔", "tools", "paint brush"),
    ("die Taschenlampe", "die Taschenlampen", "手电筒", "tools", "flashlight"),
    ("die Leiter", "die Leitern", "梯子", "tools", "ladder"),
    ("das Lineal", "die Lineale", "尺子", "stationery", "ruler"),
    ("der Bleistift", "die Bleistifte", "铅笔", "stationery", "pencil"),
    ("der Kugelschreiber", "die Kugelschreiber", "圆珠笔", "stationery", "ballpoint pen"),
    ("der Radiergummi", "die Radiergummis", "橡皮", "stationery", "eraser"),
    ("das Heft", "die Hefte", "练习本", "stationery", "notebook"),
    ("der Ordner", "die Ordner", "文件夹", "stationery", "binder folder"),
    ("die Tasche", "die Taschen", "包；袋子", "clothing", "bag"),
    ("der Rucksack", "die Rucksäcke", "背包", "clothing", "backpack"),
    ("der Schuh", "die Schuhe", "鞋", "clothing", "shoe"),
    ("die Socke", "die Socken", "袜子", "clothing", "sock"),
    ("die Hose", "die Hosen", "裤子", "clothing", "trousers pants"),
    ("das Hemd", "die Hemden", "衬衫", "clothing", "shirt"),
    ("die Jacke", "die Jacken", "夹克；外套", "clothing", "jacket"),
    ("der Mantel", "die Mäntel", "大衣", "clothing", "coat"),
    ("der Schal", "die Schals", "围巾", "clothing", "scarf"),
    ("der Handschuh", "die Handschuhe", "手套", "clothing", "glove"),
    ("die Mütze", "die Mützen", "帽子", "clothing", "cap hat"),
    ("der Apfel", "die Äpfel", "苹果", "food", "apple fruit"),
    ("die Banane", "die Bananen", "香蕉", "food", "banana"),
    ("die Birne", "die Birnen", "梨", "food", "pear fruit"),
    ("die Tomate", "die Tomaten", "番茄", "food", "tomato"),
    ("die Gurke", "die Gurken", "黄瓜", "food", "cucumber"),
    ("die Karotte", "die Karotten", "胡萝卜", "food", "carrot"),
    ("die Zwiebel", "die Zwiebeln", "洋葱", "food", "onion"),
    ("der Knoblauch", "die Knoblauchknollen", "大蒜", "food", "garlic"),
    ("das Brot", "die Brote", "面包", "food", "bread"),
    ("die Butter", "die Butter", "黄油", "food", "butter"),
    ("die Milch", "die Milch", "牛奶", "food", "milk bottle"),
    ("das Ei", "die Eier", "鸡蛋", "food", "egg"),
    ("der Fisch", "die Fische", "鱼", "food", "fish food"),
    ("das Fleisch", "die Fleischsorten", "肉", "food", "meat"),
    ("der Zucker", "die Zuckersorten", "糖", "food", "sugar"),
    ("das Salz", "die Salze", "盐", "food", "salt"),
    ("der Einkaufswagen", "die Einkaufswagen", "购物车", "shopping", "shopping cart"),
    ("der Korb", "die Körbe", "篮子", "shopping", "basket"),
    ("die Kasse", "die Kassen", "收银台", "shopping", "cash register checkout"),
    ("die Dose", "die Dosen", "罐头；罐子", "shopping", "can tin"),
    ("die Tüte", "die Tüten", "袋子", "shopping", "shopping bag"),
    ("das Preisschild", "die Preisschilder", "价格标签", "shopping", "price tag"),
    ("die Batterie", "die Batterien", "电池", "electronics", "battery"),
    ("das Ladegerät", "die Ladegeräte", "充电器", "electronics", "charger"),
    ("das Kabel", "die Kabel", "电缆；线", "electronics", "cable wire"),
    ("der Stecker", "die Stecker", "插头", "electronics", "electrical plug"),
    ("die Steckdose", "die Steckdosen", "插座", "electronics", "power outlet"),
    ("die Fernbedienung", "die Fernbedienungen", "遥控器", "electronics", "remote control"),
]

MARKET_FOOD_ITEMS = [
    ("die Kartoffel", "die Kartoffeln", "土豆", "vegetables", "potato"),
    ("die Süßkartoffel", "die Süßkartoffeln", "红薯；甜土豆", "vegetables", "sweet potato"),
    ("die Paprika", "die Paprikas", "彩椒；甜椒", "vegetables", "bell pepper"),
    ("der Brokkoli", "die Brokkoli", "西兰花", "vegetables", "broccoli"),
    ("der Blumenkohl", "die Blumenkohle", "花椰菜", "vegetables", "cauliflower"),
    ("der Kohl", "die Kohle", "卷心菜", "vegetables", "cabbage"),
    ("der Rotkohl", "die Rotkohle", "红甘蓝", "vegetables", "red cabbage"),
    ("der Weißkohl", "die Weißkohle", "白卷心菜", "vegetables", "white cabbage"),
    ("der Spinat", "die Spinatsorten", "菠菜", "vegetables", "spinach"),
    ("der Salat", "die Salate", "生菜；沙拉菜", "vegetables", "lettuce"),
    ("der Kopfsalat", "die Kopfsalate", "结球生菜", "vegetables", "head lettuce"),
    ("der Rucola", "die Rucolas", "芝麻菜", "vegetables", "arugula rocket salad"),
    ("der Lauch", "die Lauchstangen", "韭葱；大葱", "vegetables", "leek"),
    ("der Sellerie", "die Selleries", "芹菜", "vegetables", "celery"),
    ("die Aubergine", "die Auberginen", "茄子", "vegetables", "eggplant aubergine"),
    ("die Zucchini", "die Zucchini", "西葫芦", "vegetables", "zucchini courgette"),
    ("der Champignon", "die Champignons", "蘑菇；双孢蘑菇", "vegetables", "button mushroom"),
    ("das Radieschen", "die Radieschen", "樱桃萝卜", "vegetables", "radish"),
    ("der Spargel", "die Spargelstangen", "芦笋", "vegetables", "asparagus"),
    ("die Bohne", "die Bohnen", "豆角；豆子", "vegetables", "green beans"),
    ("die Erbse", "die Erbsen", "豌豆", "vegetables", "peas"),
    ("der Mais", "die Maiskolben", "玉米", "vegetables", "corn cob"),
    ("die Orange", "die Orangen", "橙子", "fruit", "orange fruit"),
    ("die Zitrone", "die Zitronen", "柠檬", "fruit", "lemon"),
    ("die Limette", "die Limetten", "青柠", "fruit", "lime fruit"),
    ("die Erdbeere", "die Erdbeeren", "草莓", "fruit", "strawberry"),
    ("die Himbeere", "die Himbeeren", "树莓", "fruit", "raspberry"),
    ("die Heidelbeere", "die Heidelbeeren", "蓝莓", "fruit", "blueberry"),
    ("die Traube", "die Trauben", "葡萄", "fruit", "grapes"),
    ("der Pfirsich", "die Pfirsiche", "桃子", "fruit", "peach fruit"),
    ("die Pflaume", "die Pflaumen", "李子", "fruit", "plum fruit"),
    ("die Kirsche", "die Kirschen", "樱桃", "fruit", "cherry fruit"),
    ("die Melone", "die Melonen", "甜瓜", "fruit", "melon"),
    ("die Wassermelone", "die Wassermelonen", "西瓜", "fruit", "watermelon"),
    ("die Mango", "die Mangos", "芒果", "fruit", "mango"),
    ("die Hähnchenbrust", "die Hähnchenbrüste", "鸡胸肉", "meat", "chicken breast"),
    ("der Hähnchenschenkel", "die Hähnchenschenkel", "鸡腿", "meat", "chicken leg"),
    ("die Putenbrust", "die Putenbrüste", "火鸡胸肉", "meat", "turkey breast"),
    ("das Hackfleisch", "die Hackfleischsorten", "肉末", "meat", "ground meat minced meat"),
    ("das Rinderhackfleisch", "die Rinderhackfleischsorten", "牛肉末", "meat", "ground beef"),
    ("das Rindersteak", "die Rindersteaks", "牛排", "meat", "beef steak"),
    ("das Schweinekotelett", "die Schweinekoteletts", "猪排", "meat", "pork chop"),
    ("der Schweinebauch", "die Schweinebäuche", "五花肉；猪腹肉", "meat", "pork belly"),
    ("der Speck", "die Specksorten", "培根；熏肉", "meat", "bacon"),
    ("die Bratwurst", "die Bratwürste", "煎香肠", "meat", "bratwurst sausage"),
    ("die Salami", "die Salamis", "萨拉米香肠", "meat", "salami"),
    ("der Schinken", "die Schinken", "火腿", "meat", "ham"),
    ("die Leberwurst", "die Leberwürste", "肝肠", "meat", "liver sausage"),
    ("das Schnitzel", "die Schnitzel", "炸肉排；肉排", "meat", "schnitzel"),
    ("der Lachs", "die Lachse", "三文鱼", "seafood", "salmon fillet"),
    ("der Thunfisch", "die Thunfische", "金枪鱼", "seafood", "tuna fish"),
    ("die Garnele", "die Garnelen", "虾", "seafood", "shrimp prawn"),
    ("der Käse", "die Käsesorten", "奶酪", "dairy", "cheese"),
    ("der Joghurt", "die Joghurts", "酸奶", "dairy", "yogurt cup"),
    ("der Quark", "die Quarksorten", "夸克奶酪", "dairy", "quark dairy"),
    ("die Sahne", "die Sahnen", "奶油", "dairy", "cream carton"),
    ("der Schmand", "die Schmandsorten", "酸奶油", "dairy", "sour cream"),
    ("der Frischkäse", "die Frischkäse", "奶油奶酪", "dairy", "cream cheese"),
    ("der Mozzarella", "die Mozzarellas", "马苏里拉奶酪", "dairy", "mozzarella cheese"),
    ("der Gouda", "die Goudas", "高达奶酪", "dairy", "gouda cheese"),
    ("das Brötchen", "die Brötchen", "小面包", "bakery", "bread roll"),
    ("das Croissant", "die Croissants", "可颂", "bakery", "croissant"),
    ("das Toastbrot", "die Toastbrote", "吐司面包", "bakery", "toast bread"),
    ("das Vollkornbrot", "die Vollkornbrote", "全麦面包", "bakery", "whole grain bread"),
    ("das Baguette", "die Baguettes", "法棍", "bakery", "baguette"),
    ("der Kuchen", "die Kuchen", "蛋糕", "bakery", "cake"),
    ("die Chips", "die Chips", "薯片", "snacks", "potato chips bag"),
    ("die Salzstange", "die Salzstangen", "咸味脆棒", "snacks", "pretzel sticks"),
    ("die Brezel", "die Brezeln", "德国椒盐卷饼", "snacks", "pretzel"),
    ("der Keks", "die Kekse", "饼干", "snacks", "cookie biscuit"),
    ("die Schokolade", "die Schokoladen", "巧克力", "snacks", "chocolate bar"),
    ("das Gummibärchen", "die Gummibärchen", "小熊软糖", "snacks", "gummy bears"),
    ("der Müsliriegel", "die Müsliriegel", "谷物棒", "snacks", "granola bar"),
    ("die Nuss", "die Nüsse", "坚果", "snacks", "nuts"),
    ("die Erdnuss", "die Erdnüsse", "花生", "snacks", "peanuts"),
    ("die Mandel", "die Mandeln", "杏仁", "snacks", "almonds"),
    ("das Popcorn", "die Popcornsorten", "爆米花", "snacks", "popcorn"),
    ("das Eis", "die Eissorten", "冰淇淋", "snacks", "ice cream"),
    ("der Saft", "die Säfte", "果汁", "drinks", "juice carton"),
    ("der Apfelsaft", "die Apfelsäfte", "苹果汁", "drinks", "apple juice carton"),
    ("der Orangensaft", "die Orangensäfte", "橙汁", "drinks", "orange juice carton"),
    ("das Wasser", "die Wasser", "水", "drinks", "water bottle"),
    ("das Mineralwasser", "die Mineralwasser", "矿泉水", "drinks", "mineral water bottle"),
    ("die Limonade", "die Limonaden", "汽水", "drinks", "lemonade bottle"),
    ("das Bier", "die Biere", "啤酒", "drinks", "beer bottle"),
    ("der Kaffee", "die Kaffees", "咖啡", "drinks", "coffee package"),
    ("der Tee", "die Tees", "茶", "drinks", "tea box"),
    ("die Nudeln", "die Nudeln", "意面；面条", "pantry", "pasta"),
    ("der Reis", "die Reissorten", "米", "pantry", "rice bag"),
    ("das Mehl", "die Mehlsorten", "面粉", "pantry", "flour bag"),
    ("die Haferflocke", "die Haferflocken", "燕麦片", "pantry", "rolled oats"),
    ("das Müsli", "die Müslis", "谷物麦片", "pantry", "muesli cereal"),
    ("die Marmelade", "die Marmeladen", "果酱", "pantry", "jam jar"),
    ("der Honig", "die Honige", "蜂蜜", "pantry", "honey jar"),
    ("das Öl", "die Öle", "油", "pantry", "cooking oil bottle"),
    ("der Essig", "die Essige", "醋", "pantry", "vinegar bottle"),
    ("der Senf", "die Senfsorten", "芥末酱", "pantry", "mustard jar"),
    ("der Ketchup", "die Ketchups", "番茄酱", "pantry", "ketchup bottle"),
    ("die Mayonnaise", "die Mayonnaisen", "蛋黄酱", "pantry", "mayonnaise jar"),
]

RAW_ITEMS.extend(MARKET_FOOD_ITEMS)


DOMAIN_LABELS = {
    "kitchen": "厨房",
    "bathroom": "浴室",
    "furniture": "家具家居",
    "tools": "工具",
    "stationery": "文具",
    "clothing": "衣物",
    "food": "食物",
    "vegetables": "蔬菜",
    "fruit": "水果",
    "meat": "肉类",
    "seafood": "海鲜鱼类",
    "dairy": "乳制品",
    "bakery": "面包点心",
    "snacks": "零食",
    "drinks": "饮料",
    "pantry": "调料干货",
    "shopping": "超市购物",
    "electronics": "电子用品",
}


def make_entry(article_lemma: str, plural: str, zh: str, domain: str, image_query: str) -> EntryCreate:
    article, lemma = article_lemma.split(" ", 1)
    gender = {"der": "der", "die": "die", "das": "das"}[article]
    domain_label = DOMAIN_LABELS[domain]
    return EntryCreate(
        lemma=lemma,
        part_of_speech="noun",
        word_category="concrete_object",
        article=article,
        gender=gender,
        plural_form=plural,
        cefr_level="A1" if domain in {"food", "furniture", "clothing"} else "A2",
        source_type="life_objects_seed",
        meanings=[{"language": "zh", "gloss": zh}],
        forms=[{"label": "plural", "value": plural}],
        examples=[
            {
                "german_text": f"Das ist {article_lemma}.",
                "chinese_text": f"这是{zh}。",
            }
        ],
        tags=[
            {"name": "生活实物", "tag_type": "日常生活"},
            {"name": domain_label, "tag_type": "日常生活"},
            {"name": "名词", "tag_type": "语言属性"},
        ],
        extra_data={"image_search_query": image_query, "domains": [domain, "daily_objects"]},
    )


def main() -> None:
    Base.metadata.create_all(bind=engine)
    payloads = [make_entry(*item) for item in RAW_ITEMS]
    with SessionLocal() as session:
        imported = upsert_entries(session, payloads)
    print(f"Imported or updated {imported} life object entries.")


if __name__ == "__main__":
    main()
